// Import Libraries
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { createTheme, MantineProvider, ColorSchemeScript } from '@mantine/core';
// Import Styles
import '@/styles/globals.scss';
import styles from '@/app/layout.module.scss';
// Import Components
import Sidebar from '@/components/layout/Sidebar';

// 1. Cấu hình Font Inter
const inter = Inter({
  subsets: ['latin', 'vietnamese'], // Bắt buộc có vietnamese để đọc tiếng Việt không lỗi
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  variable: '--font-inter', // Tạo biến CSS để SCSS có thể dùng được
});

// 2. Cấu hình Mantine Theme
const theme = createTheme({
  fontFamily: inter.style.fontFamily, // Áp dụng font Inter cho toàn bộ Mantine
  // ... các config khác về màu sắc, spacing mày đã làm
});

export const metadata: Metadata = {
  title: 'VNINSIGHTS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={inter.variable}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <div className={styles.layoutWrapper}>
            <Sidebar />
            <main className={styles.mainContent}>{children}</main>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
